# Generated by Django 3.2.5 on 2021-09-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210927_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
